{
 "title": "Flink Job Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Taxi Job busyTimeMsPerSecond",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(job_name) (flink_taskmanager_job_task_busyTimeMsPerSecond{job_name=\"Taxi_Job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxi Job RecordsOutPerSecond (Subtasks)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(subtask_index) (flink_taskmanager_job_task_numRecordsOutPerSecond{job_name=\"Taxi_Job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxi Job RecordsOutPerSecond",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(job_name) (flink_taskmanager_job_task_numRecordsOutPerSecond{job_name=\"Taxi_Job\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}